git-quick-stats/git-quick-stats

- git-quick-stats
Restrict the commits used in generating stats to commits that aren't merges. For repos that have lots of pull requests that are merged in it can really throw off the statistics.
> restrict to non-merge commits

- git-quick-stats
Currently, the menu will be shown if I run git-quick-stats outside of a git repo. Any of the options presented in the menu will fail with the error message `fatal: Not a git repository (or any of the parent directories): .git`.
This PR adds a check for a git repo before parsing any input or displaying the menu. If a git repo is not found, the error message `fatal: Not a git repository (or any of the parent directories): .git` is printed out.
I've tested this by running git-quick-stats outside of a git repo:
``` bash
$ pwd
/tmp/not-a-git-repo
$ git-quick-stats
fatal: Not a git repository (or any of the parent directories): .git
```
Running git-quick-stats inside a git repo:
```bash
$ pwd
/tmp/a-git-repo
$ git-quick-stats
Generate:
1) Contribution stats (by author)
2) Git changelogs
3) My …
```
> Exit if we are not in a git repo

- git-quick-stats
Hi, I liked your tool.  This is a slight tweak that adds basic support for reporting on commits by hour for individual authors as well.
Let me know if you have any questions/comments.
Cheers,
Brian
> adapts commitsByHour to allow reporting by author as well

- Makefile
Tested on Antergos KDE (Arch Linux)
Without supplying `-e` to `echo`, the Escape sequence `\n` is treated literally.
> Makefile: Don't treat newline characters literally

- git-quick-stats
With `git-bash` for Windows, selecting option 12 (commits by hour) without specifying an author results in the following error (for each git command, one per hour):
````
fatal: ambiguous argument '': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
````
I believe the issue is caused because `_author` (set to `''`) is being read as `''` (two quotes) instead of an empty string. I'm not sure if it's exclusive to Windows. Either way, this pull request fixed it by quoting the entire command.
> Fix ambiguous argument when author is not specified for commits by hour

- Makefile
When the variable PREFIX is provided on the command line, do not
override the value.
Signed-off-by: Dan Kalowsky <dank@deadmime.org>
> Makefile: set PREFIX to conditional assignment

- Makefile
If `$(PREFIX)` was an empty directory, `$(PREFIX)/bin` would end up
being the executable instead of a directory. Create the `bin` directory
first.
> Makefile: fix installing to an empty prefix

- git-quick-stats
In contribution stats menu, if author name has more than 2 words, it just show the 1st and the 2nd word.
Sometimes it don't show the email address of a contributor.
This pull request fix that issue.
> fix: author not show fullname in contribution stats

- git-quick-stats
While using this tool feature "Contribution stats (by author)", I observed that script was not respecting mailmap author email as option was being used here was "%ae". Corrected it to "%aE", output looks good now.
> Respect mailmap author email

- README.md
- git-quick-stats
* In some situations, the awk statements in the functions commitsByMonth,
commitsByDay, and commitsByHour attempt to divide by zero and display
an error to the user. To invoke this bug, checkout any of the previous
commits and attempt to see commits by hour from some user who has never
committed to this repository.
This commit fixes this bug by making sure the awk statement only ever
executes when the total commits is greater than zero.
* Added a utility checker to make sure that the user has all of the necessary
tools in their path in order to run this script. If they do not exist, it
exits and informs the user that this script cannot locate them in PATH.
* Adjusted shell logic to prevent double negatives from confusing developers
as ! -z is technically read as something akin to "not has …
> Fix divide by zero error and add utility checker

- git-quick-stats
* Fixing a bug where, if you insert an author's name that has a space in the
"Git commits by author per hour" option, it fails due to improper variable
expansion. Note that the current implementation is a "greedy" one in that
it will attempt to look for any instance of the user provided string in the
author field
> Fix bug related to author name in hourly stats

- README.md
- git-quick-stats
- tests/commands_test.sh
* The previous commands were Lower CamelCase style and had no equivalent
short options. If you wanted to see the branch tree via non-interactive
mode, you always needed to supply "branchTree" as the passing argument to
the git-quick-stats script.
This commit changes the argument style to be more akin to the POSIX and GNU
styles of arguments commonly seen in many other applications. As of this
commit, there is no compatibility with legacy commands, so those who have
been using the old commands will unfortunately need to get familiar with the
new ones. All documentation and tests have been updated accordingly to
reflect the new changes.
* The main interactive loop contained a non-variable constant that was only
getting parsed correctly due to legacy fallback behavior. This commit fixes
the …
> Changed non-interactive args and fixed main loop

- git-quick-stats
* When someone has the showSignature=true flag set in their .gitconfig
file, gpg verifying signature related text would be parsed as if it
was actual log information. This change ignores signature-related text
by passing the -c log.showSignature=false option to git so it ignores
a user's custom .gitconfig showSignature flag regardless as to what it
is set to.
Resolves: Issue #52
> Fixed issue where signatures were parsed in logs

- git-quick-stats
* All internal functions now have documentation describing what they are,
what arguments they take, and what external variables are set in an effort
to help others understand the codebase more quickly
* Changed a few lines where grep | wc -l occurred, as grep has a built-in
option to do this: grep -c
* Removed a $* where the suggestReviewers function expected a string but
never received one during the life of the program
* Adjusted some lines so they weren't quite as long, adjusted some variable
names, and other minor cleanup
> Added internal documentation and minor cleanup

- README.md
- git-quick-stats
- git-quick-stats.1
The format _GIT_SINCE is what `git --since` takes in which is YYYY-MM-DD.
Ref: https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
> Change format of _GIT_SINCE in help

- Makefile
This is more standard than forcing the user to specify the destination
directory as part of PREFIX.
> make: Use DESTDIR

- README.md
Hyphens are necessary for compound adjectives
> Update text errors from README.md

- git-quick-stats
Include contribution by co-authors (`Co-authored-by`) in the **commitsPerAuthor** option.  
Fixes : https://github.com/arzzen/git-quick-stats/issues/70
> Support commits by co-authors

- git-quick-stats
putting checked utils into array and running through the array in for loop cleans the code
> refactor checkUtils: remove repeating commands

- git-quick-stats
* OS X utilizes an older version of GNU Bash. As such, certain features
such as lowercase expansion can fail. This commit removes the Bash 4.0
syntax in favor of a POSIX syntax with awk.
> Fixing OS X compatibility with merge feature

- git-quick-stats
* If a space existed within _GIT_SINCE, _GIT_UNTIL, or _GIT_PATHSPEC,
the shell would split the variable at the first space it saw because
the variables were not quoted.
If you were to simply quote the variables, then a null variable would
get inserted into git's log, and it would cause an error.
This change adds default values to these variables at all times so
the variables are always assigned to something that git understands.
Fixes #95
> Fix issue with env vars not respecting spaces

- git-quick-stats
* A new feature was implemented to show percentages when displaying
detailed stats (menu options 1 and 2, or options -T and -R).
However, the calculation during "lines changed" may cause an error
within awk stating it cannot divide by zero as there is no check
to see if the divisor is larger than zero.
This commit attempts to fix that issue, albeit admittedly not in
the most elegant way...
Tested on macOS 10.14, Ubuntu 16.04, and Fedora 30
> Fix divide by zero error during lines changed calc

- git-quick-stats
* There was an issue with quoting in the pathspec variable where
the variable would get mangled when being passed to different
parameters during git operations. This change fixes that.
Fixes #102
> Fix folder excluding pathspec bug #102

- README.md
- git-quick-stats
- git-quick-stats.1
- tests/commands_test.sh
A new feature was implemented which can use additional `git log` options.
You can set `_GIT_LOG_OPTIONS` variable to use git log options, 
eg: `export _GIT_LOG_OPTIONS="--ignore-all-space 
--ignore-cr-at-eol"`
See all `git log` options https://git-scm.com/docs/git-log#_options.
Tested on Ubuntu 16.04, Ubuntu 18.04 and Windows 10
Resolves #104
> Ability to use options for git log command

- git-quick-stats
Remove non-POSIX shell features from `checkUtils()` as these result in error during execution in a POSIX compliant shell (e.g. ash). 
1. https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_05
2. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html22
> checkUtils: remove non-POSIX compliant features

- git-quick-stats
Remove non-POSIX shell features from `usage()` as these result in error during execution in a POSIX compliant shell (e.g. ash). 
1. https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_09_05
2. https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html22
> usage: remove non-POSIX compliant features

- git-quick-stats
Hello.
In some (most European) locales, the decimal number part delimiter is actually a comma (`,`), while in other countries (UK, US, Asian) it is a dot (`.`): https://en.wikipedia.org/wiki/Decimal_separator
This breaks representation of percentage value of commits per author output. See here:
```
$ git-quick-stats --commits-per-author | head
Git commits per author:
106  Lukas Mestan              58  2%
22   Tom Ice                   12  1%
7    Miodrag Tokić             3   8%
6    jdeguzman                 3   3%
4    Joshua de Guzman          2   2%
3    Michael Czigler           1   6%
2    Sandro                    1   1%
2    Joopmicroop               1   1%
```
The fractional part of the last column got separated with space.
In `C` locale all is correct:
```
$ LANG=C …
```
> fix: correct localized decimal percent numbers

- tests/assert.sh
- tests/commands_test.sh
Hi,
This PR fixes tests based on `assert_contains`.
If you just specify *any random string* as an argument to the function, the tests just pass, which is not how it supposed to work.
There are few problems discovered in the test script.
Facts:
* `assert_contains` calls `_assert_with_grep` which calls `assert_raises`, which should use `grep` for testing
* `assert_contains` gets exit code as a third argument which is passed to `assert_raises`
Problems:
* The exit code `127` is passed to final `assert_raises` call, but `grep` (according to the man page) does not return such code ever.
* Seems to be that `$GREP` variable was not initialized and being substituted by empty string, so exit code `127` come out from the shell as "command not found" error.
* Testing with exit code seems to be …
> test: fix assert_contains and its invocation

- git-quick-stats
* The current default date is set to UNIX Epoch time. However, it seems
some people are possibly having issues with date/time formats within
their OSes. This commit attempts to fix issue #115 when the default
date may be too old and cause no output to show
> Change default date to be when git was first invented

- git-quick-stats
* When performing actions such as redirecting the stats to a file,
the terminal escape sequences for handling colors gets added
to the top message in the text file. While running commands such
as sed can fix this, it is inconvenient for users wishing to redirect
or pipe the stats in a clean way.
Attempting to use test -t yielded some unexpected results, as well
as extra logic for handling a non-tty case, so for now, we are
simply removing the colors from the message so it defaults to
standard terminal colors and formatting
Fixes #122
> Fix escape sequences when outputting to non-TTYs

- git-quick-stats
Solving #126 
myDailyStats() used grep commit to detect count of commits. This
also increases the count by mentioning commit in the commit
message.
Therefore a grep with regex is used that expects a 40 digit/char
SHA1 hash after the word commit.
> Replaced grep commit by grep with regex including git sha hash

- Makefile
- README.md
- git-quick-stats
- git-quick-stats.1
- tests/assert.sh
- tests/commands_test.sh
- The start date was arbitrary at 2005, changed to actual first commit.
- Filter by years in by-month and by-week was incorrectly used eg #135
- Other greps also could match on [0-9]{4} in commit (hash or message)
- Added commits-by-year histogram
> Misc. fixes on filtering, added commits-by-year

- git-quick-stats
when grouping by author -L, I found it hard to read YYYY-MM-DD, so added day name to that.
> add day name to date

- git-quick-stats
This is required for changelogs.
Resolves #147
---
Only tested on Ubuntu and Windows (MINGW64 from Git Bash):
```bash
$ date --version
date (GNU coreutils) 8.32
…
$ date --help | grep '\-d'
-d, --date=STRING          display time described by STRING, not 'now'
…
```
Could anyone help to test on FreeBSD?
> fix: Ubuntu does not support `date -j`

- README.md
> docs: Document default `_GIT_LIMIT` value

- git-quick-stats
I found that on Fedora 37, trying to get commits sorted by timezone gave some weird results. For example, on this repo:
```
[root@279546d667cd git-quick-stats]# git-quick-stats -z
Git commits by timezone:
Commits	TimeZone
1 "git
1 #25
1 #4
1 %(color
1 ->
1 DESTDIR
1 Git
1 PREFIX
1 URLs
1 X
1 _exclude
1 and
1 args
2 argument
1 assert_contains
[...]
```
It seems that even with `--format`,  spacing output from `git shortlog` can vary between distros, which throws off the `cut` command. Running the timezone command in a Fedora container will give the above (the correct field number is 9 in this case), but running on a Ubuntu container works as expected:
```
root@124446510da3:/git-quick-stats# git-quick-stats -z
Git commits by timezone:
Commits	TimeZone
6 +0000
81 +0100
53 +0200
1 +0300
2 …
```
> Update formatting and sort commits by timezone

- git-quick-stats
Calculate the day before the given since date, as it excludes the given date the inclusion is wanted.
fixes #41
> calculate the day before the given since date

- git-quick-stats
- git-quick-stats.1
- tests/commands_test.sh
- tests/test-git/resetgit
* Users on macOS and other older distributions of Linux and Unix cannot fully utilize this application as a handful of date/time strings in here are specific to the GNU utility found on most modern version of Linux.
Until every date/time case is handled between the BSD version of date and the GNU version of date, let's error out akin to how we do it if the user doesn't have every utility installed to run this script.
Users can get around this by using package managers on macOS such as homebrew, macports, etc and making sure that 'date' points to the GNU version of date instead of the BSD version. Linux and Unix users can get around this by installing the GNU version of date, as well.
* Removed checking OSTYPE in the format_date() function as checking if someone is on a machine that …
> Handle error where BSD date is being used

- README.md
- git-quick-stats
- git-quick-stats.1
- tests/commands_test.sh
This reports generates a list of all contributors whose first commit was after a specified date.
I've tested this with several date formats, including invalid ones, and added a check of the date prior to trying to use it.
Fixes #169
> Add a list of new contributors

- git-quick-stats
* commitsByYear() previously could only support Default-style dates for git log. However, a user can use a variety of different date formats such as relative, default, iso, rfc, short, and raw.
This change modifies commitsByYear() to handle multiple different date strings
Fixes #172
> Adjust commitsByYear() to support multiple dates

- git-quick-stats
* Original function lacked explicit sorting by time. Adding sorting by time within the same day to help make changelogs consistent.
* Removed format_date() and brought its functionality back into changelogs() as it wasn't used anywhere else
Fixes #161
> Address inconsistency in changelogs

- Dockerfile
When bind-mounting a Git repository to the workdir, Git would complain about 'dubious ownership'.
We add an exception to the global Git config, in the way Git tells us to. This should be safe since
- we run in a container, and
- the user can set the mount to read-only.
fixes issue #179
> fix(docker): tell Git that the workdir is safe

- git-quick-stats
Fixes:
```console
$ git clone -q https://github.com/util-linux/util-linux.git
$ git -C util-linux quick-stats -a | grep -w uthor
23    uthor                                    Karel Zak              0.1%
3     uthor                                    Ondrej Oprala          0.0%
2     uthor                                    Samuel Thibault        0.0%
...
```
> Anchor regexps in commitsPerAuthor()

- git-quick-stats
While checking the tests for #186, I got an error-message from `seq` about an invalid argument.
I have traced it back to the default `until`-date not being properly parsed when the system-locale is not English (German in my case).
This is a problem in normal operation as well:
```console
$ ./git-quick-stats -Y
Git commits by year:
year	sum
seq: ungültiges Gleitkommaargument: »«
„seq --help“ liefert weitere Informationen.
```
(Error-message translates to `invalid floating-point argument ""`)
This is because `date` (used for setting the default `until`-date) produces localized output by default.
However, `date -d` cannot parse this localized output but requires a [locale independent format](https://www.gnu.org/software/coreutils/manual/html_node/Options-for-date.html#index-_002dd-19).
This …
> Fix default until-date in other locales
