git-quick-stats

It's often useful to know all the activity periods of each one of the authors.

Add first -> last commits for each author.

---

git-quick-stats

The current user interface seems to place options in no particular order, which slows down the user's workflow. By providing some more organization, the learning curve will be easier for new users. In order to test the changes, I've entered each option and verified the appropriate output and action.
* Provide a hierarchy of verbs for the corresponding set of options.
* Alphabetize menu options for a second layer of organization.
* Simplify option statements and change the corresponding output in the appropriate places.
* Reorder mapping of number to function in the main while loop.

Organize and simplify user interface

---

README.md
git-quick-stats

A handy tree view of your branches and latest commits, easy and visual way of branching

added branchTree command and changed README.md

---

git-quick-stats

awk division by zero #16

---

git-quick-stats

added november to the list of months

---

git-quick-stats

Fixes https://github.com/arzzen/git-quick-stats/issues/37

Fix error on whitespace in author name

---

README.md

Just some minor text edits. Didn’t mean to nitpick, sorry if it comes off that way. 😇 
**Edit**: Only now realising I had my editor set to delete whitespace at the end of lines… hence more changes than the two I made are in the diff. Sorry for missing that. But don’t think it’s anything critical. 🤞

Fixes minor typos

---

README.md
git-quick-stats

* Color was originally done with ANSI escape characters for defining
different "expected" colors. However, this is not uniform across all
terminals. To improve what the designers of this program expect
colors to be, escape codes were replaced with tput equivalents.
For more information, see the GNU manual here:
https://www.gnu.org/software/termutils/manual/termutils-2.0/html_chapter/tput_1.html
* Limited scope of variables to their local scope instead of having them
be global
* Renamed menu variables to aid in readability and adjusted formatting
slightly to be more uniform
* Fixed a bug where option_picked was assigning an array to a string
and relying on the default behavior of the shell to interpret it
* Added the -r option to "read" for safety, as read without -r will
interpret …

Improve color compatibility and other minor fixes

---

git-quick-stats

Fix some items are not displayed

---

.travis.yml

update travis yml

---

git-quick-stats

Fix inconsistent sum sorting in by-weekday, #91

Update commitsByWeekday sorting

---

git-quick-stats

- [#123] fixed parse `git shortlog ` by particular year

fix shortlog filter

---

README.md
git-quick-stats
git-quick-stats.1
tests/commands_test.sh

Adds the possibility to specify the branch to be taken into account for statistics.

Add git branch option

---

README.md
git-quick-stats
git-quick-stats.1
tests/commands_test.sh

I need to be able to export the stats in a parsable format. 
For example, to exploit them via another script which will be able to concatenate the stats of several repositories

Export CSV of detailedGitStats

---

README.md
git-quick-stats
git-quick-stats.1
tests/commands_test.sh

Implements the enhancement requested in #128 . @arzzen When you get a moment, could you double-check and triple-check everything? I made a lot of changes internally, and I may have missed something. Thanks!

Add stat by author per timezone functionality

---

tests/commands_test.sh

Hi! I found a typo in the test that is causing it to fail.
`make test` log without this patch:
```
tests/commands_test.sh
X...........
test #1 "./git-quick-stats fail" failed:
expected "Invalid argument
NAME
git-quick-stats - Simple and efficient way to access various stats in a git repo
SYNOPSIS
For non-interactive mode: git-quick-stats [OPTIONS]
For interactive mode: git-quick-stats
DESCRIPTION
Any git repository contains tons of information about commits, contributors,
and files. Extracting this information is not always trivial, mostly because
of a gadzillion options to a gadzillion git commands.
This program allows you to see detailed information about a git repository.
GENERATE OPTIONS
-T, --detailed-git-stats
give a detailed list of git stats
-R, --git-stats-by-branch
see detailed …
```

test: fix a typo in the 1st test

---

git-quick-stats

Fix date - day name

---

git-quick-stats

relates to https://github.com/Homebrew/homebrew-core/pull/170269

improve macos error message wrt gnu date

---

README.md
git-quick-stats

* Added additional information to better explain how to use this on macOS.
* Updated some of the deps used
* Minor adjustments in the README.md
Addresses Issue #166

Update documentation for clarity

---

git-quick-stats

Fix typo in JSON output
